<?php

namespace App\Test;

use PHPUnit\Framework\TestCase;
use App\System;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-28 at 22:28:50.
 */
class SystemTest extends TestCase
{

    /**
     *
     * @var type 
     */
    public $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = $this->getMockForTrait(System::class);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * 
     */
    public function testRandom()
    {
        // WHEN
        $actual1 = $this->object->rand(1, 2);
        $actual2 = $this->object->rand(1);
        $actual3 = $this->object->rand();

        // THEN
        $this->assertGreaterThanOrEqual(1, $actual1);
        $this->assertLessThanOrEqual(2, $actual1);

        $this->assertGreaterThanOrEqual(1, $actual2);
        $this->assertLessThanOrEqual(getrandmax(), $actual2);

        $this->assertGreaterThanOrEqual(0, $actual3);
        $this->assertLessThanOrEqual(getrandmax(), $actual3);
    }

    /**
     * 
     */
    public function testCreateObject()
    {
        $datetime = $this->object->createObject('\DateTime');
        $this->assertInstanceOf('\DateTime', $datetime);
        $this->assertEquals(time(), $datetime->getTimeStamp());

        $std = $this->object->createObject('\stdClass');
        $this->assertInstanceOf('\stdClass', $std);
    }

}
